### ISSUE TITLE
create a navigation drop box for versions after header

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/decenter-ai.streamlit.app#11]
Update:

Overview:

![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/24226219/357c2bba-20a2-4103-9908-89072f3ef2fc)

![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/24226219/c17c7bf6-1d8e-409c-a526-f54ca5644334)

Dropdown for versions

![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/24226219/2c80f6f0-61f6-4a67-87f3-4feef6073a2d)

https://docs.streamlit.io/library/api-reference/widgets/st.selectbox

**Comment by Dineshjnld** [comment]
![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/106725225/7dcd9f00-2182-4eab-9a9f-50dccd68f8ea)



![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/106725225/8a0640f6-0044-4c87-bd3a-d8c2e3b4a37e)



![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/106725225/cb9a8d7a-5bf2-4ebf-b6d2-bb78d91ee2f0)

**Comment by Nasfame** [comment]
Fixed in #13
