### ISSUE TITLE
Implement automated testing for our app

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/decenter-ai.streamlit.app#12]
Refer: https://blog.devgenius.io/testing-streamlit-a1f1fd48ce8f

Req:

Wait Until Page Contains    Test
    Page Should Contain     You selected v3.
    Click Element       //*[contains(text(),'v2','v1')]
    sleep   1
    Page Should Contain     You didn't select comedy.
    Close Browser

**Comment by Nasfame** [comment]
@RedValis hope u r blocked now

**Comment by RedValis** [comment]
Updated feat/automated-testing with v3 app testing, working, tests training and downloading
