### ISSUE TITLE
proposal: demo dropdown

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/decenter-ai.streamlit.app#56]
# Proposal:

Add a demo dropdown at top right

1. Choose b/ any kaggle input archives (dynamics, u should os.listdir() all the zip files in kaggle/inputs directory)

![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/24226219/0eb38bd5-33c8-4e75-a96a-44cf9bdfac0d)

![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/24226219/d35bf374-3dac-4e6f-ba5b-8c9726e554c4)

2. When choosing one, u should be able to inject the archive.

**Comment by Dineshjnld** [comment]
_what about the position??
is it ok?_


![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/106725225/cd0ee085-5eea-4b2d-87a2-a48ae4eaf392)

**selectbox:**

![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/106725225/424cdc69-0cef-4650-b20e-8bd0d34d8a1c)


**I have slected the Winequality**
![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/106725225/ae6585fa-b2e2-484a-b048-128132cfc776)


**Executed successfully**

![Image](https://github.com/DeCenter-AI/decenter-ai.streamlit.app/assets/106725225/0eed9397-9c17-47e8-b7ef-394c55b0ab44)
