### ISSUE TITLE
CI: robot tests

### ISSUE THREAD

**Issue by Nasfame** [DeCenter-AI/decenter-ai.streamlit.app#73]
update: 

- [x] create .github/workflows/automated-robot-tests.yml 
- [x] refer: https://github.com/marketplace/actions/robot-framework or https://github.com/marketplace/actions/robot-framework-action
- [x] implement them
- [x] make sure the below code is in the workflow (.yml) file

```
on:
  pull_request:
  push: 
```

**Comment by RedValis** [comment]
Test workflow once more before closing issue
